name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x' # Specify your Node.js version
        registry-url: 'https://registry.npmjs.org/'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Run tests
      run: pnpm test

    - name: Publish RC to npm
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Get current version (remove quotes if present)
        current_version=$(pnpm pkg get version | tr -d '"')
        # Construct new version string
        new_version="$current_version-rc.${{ github.run_number }}"
        echo "Setting version to $new_version"
        # Set authentication token for npm (needed for version and publish)
        pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        # Update package.json with the new version
        pnpm version $new_version --git-tag-version=false
        # Publish the package with the 'rc' tag
        pnpm publish --tag rc --no-git-checks
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
